# Generated by Django 4.2.5 on 2023-10-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entry_remove_project_id_project_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
