# Generated by Django 4.2.5 on 2023-10-10 16:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectinvitetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='optimized_image',
        ),
        migrations.AddField(
            model_name='entrydetails',
            name='image',
            field=models.ImageField(default='str', upload_to=api.models.resolve_pathname),
            preserve_default=False,
        ),
    ]
