# Generated by Django 4.2.5 on 2023-10-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_entry_image_remove_entry_optimized_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydetails',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.entry'),
        ),
    ]
